name: microservicetemplate
services:
  dotnet-webapi:
    image: genocs/dotnet-webapi:latest
    container_name: dotnet-webapi
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
      - DatabaseSettings__ConnectionString=Server=postgres;Port=5433;Database=genocs_db;User Id=posgresqladmin;Password=posgresqladmin
      - HangfireSettings__Storage__ConnectionString=Server=postgres;Port=5433;Database=genocs_db;User Id=posgresqladmin;Password=posgresqladmin
      - DatabaseSettings__DBProvider=postgresql
      - HangfireSettings__Storage__StorageProvider=postgresql
    ports:
      - 5100:8080
      
    networks:
      - genocs
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - postgres
    restart: on-failure

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=posgresqladmin
      - POSTGRES_PASSWORD=posgresqladmin
      - PGPORT=5433
    ports:
      - 5433:5433
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - genocs
    # network_mode: host
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  genocs:
    name: genocs-network
    driver: bridge

  postgres:
    driver: local
