name: microservicetemplate
services:
  dotnet-webapi:
    image: genocs/dotnet-webapi:latest
    container_name: dotnet-webapi
    environment:
      - DatabaseSettings__ConnectionString=Server=mssql;Database=genocs_db;User=sa;Password=123Pa$$word!;MultipleActiveResultSets=true;Encrypt=false
      - HangfireSettings__Storage__ConnectionString=Server=mssql;Database=genocs_db;User=sa;Password=123Pa$$word!;MultipleActiveResultSets=true;Encrypt=false
      - DatabaseSettings__DBProvider=mssql
      - HangfireSettings__Storage__StorageProvider=mssql
    ports:
      - 5100:8080

    networks:
      - genocs
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      mssql:
        condition: service_healthy
    restart: on-failure

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "123Pa$$word!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssqlsystem:/var/opt/mssql
      - mssqluser:/var/opt/sqlserver
    healthcheck:
      test: ./opt/mssql-tools18/bin/sqlcmd -S localhost -C -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 20s
      timeout: 3s
      retries: 3
      start_period: 20s
    networks:
      - genocs

volumes:
  mssqlsystem:
    driver: local
  mssqluser:
    driver: local

networks:
  genocs:
    name: genocs-network
    driver: bridge
