name: Build test and pack

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build test and pack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore ./src/template

      - name: Build
        run: dotnet build ./src/template --no-restore

      - name: Test
        run: dotnet test ./src/template --no-build --verbosity normal

      - name: Pack
        run: dotnet pack ./src/template --no-build --verbosity normal
